spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
jwt:
  secret-key: spring-hello-world-jwt-world-hello-security
  access-token:
    expire: 600000 # 10분
  refresh-token:
    expire: 3600000 # 1시간